# -*- coding: utf-8 -*-
"""ATSA PROJECT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ji0LeClTzYt9VtVlpNBrGP4S1HtGx5it
"""



# 1. Fetch Real Data (Apple Inc. as the primary case)
ticker = "AAPL"
df_raw = yf.download(ticker, start="2016-01-01", end="2026-02-01", auto_adjust=True)

# 2. Fix for MultiIndex Columns in new yfinance versions
if isinstance(df_raw.columns, pd.MultiIndex):
    df = df_raw['Close'][[ticker]].rename(columns={ticker: 'Close'})
else:
    df = df_raw[['Close']]

# 3. Address Survivorship Bias & Real-World Friction
# We simulate a 0.1% transaction fee and 0.05% slippage
TRANSACTION_COST = 0.001
SLIPPAGE = 0.0005

# 4. Strict Train-Test Split (Zero Look-Ahead Bias)
train_size = int(len(df) * 0.8)
train_data = df.iloc[:train_size]
test_data = df.iloc[train_size:]

print(f"Dataset Loaded: {len(df)} days.")
print(f"Training Range: {train_data.index.min()} to {train_data.index.max()}")

# Prepare data for Prophet format
prophet_df = train_data.reset_index()
prophet_df.columns = ['ds', 'y']

# Initialize Expert 1
historian = Prophet(daily_seasonality=False, weekly_seasonality=True, yearly_seasonality=True)
historian.add_country_holidays(country_name='US')
historian.fit(prophet_df)

# Forecast for the test period
future = historian.make_future_dataframe(periods=len(test_data))
forecast = historian.predict(future)

# Visualize Seasonality (Critical for Evaluation 2)
historian.plot_components(forecast)
plt.show()

scaler = MinMaxScaler()
scaled_train = scaler.fit_transform(train_data)
scaled_test = scaler.transform(test_data)

def create_multi_horizon_windows(data, lookback=60, horizon_short=7, horizon_long=30):
    X, y_short, y_long = [], [], []
    for i in range(len(data) - lookback - horizon_long):
        X.append(data[i : i + lookback])
        y_short.append(data[i + lookback : i + lookback + horizon_short])
        y_long.append(data[i + lookback : i + lookback + horizon_long])
    return torch.FloatTensor(np.array(X)), torch.FloatTensor(np.array(y_short)), torch.FloatTensor(np.array(y_long))

X_train, y7_train, y30_train = create_multi_horizon_windows(scaled_train)
X_test, y7_test, y30_test = create_multi_horizon_windows(scaled_test)

train_loader = DataLoader(TensorDataset(X_train, y7_train, y30_train), batch_size=32, shuffle=True)

class HybridStockModel(nn.Module):
    def __init__(self, d_model=64, nhead=4):
        super().__init__()
        # LSTM for Momentum
        self.lstm = nn.LSTM(1, 32, batch_first=True)

        # Transformer for Global Context
        self.input_proj = nn.Linear(1, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)

        # Output Heads for 7-day and 30-day
        self.fc7 = nn.Linear(d_model + 32, 7)
        self.fc30 = nn.Linear(d_model + 32, 30)

    def forward(self, x):
        # LSTM Branch
        _, (hn, _) = self.lstm(x)
        lstm_out = hn[-1] # Final hidden state

        # Transformer Branch
        x_proj = self.input_proj(x)
        attn_out = self.transformer(x_proj)
        trans_out = attn_out[:, -1, :] # Final time step

        # Combine Experts
        combined = torch.cat((lstm_out, trans_out), dim=1)

        return self.fc7(combined), self.fc30(combined), attn_out

model = HybridStockModel()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()

# Training Loop
print("Training AI Experts (LSTM + Transformer)...")
for epoch in range(15):
    model.train()
    for b_x, b7, b30 in train_loader:
        optimizer.zero_grad()
        p7, p30, _ = model(b_x)
        loss = criterion(p7, b7.squeeze(-1)) + criterion(p30, b30.squeeze(-1))
        loss.backward()
        optimizer.step()
    if epoch % 5 == 0: print(f"Epoch {epoch} | Loss: {loss.item():.6f}")

model.eval()
with torch.no_grad():
    p7, p30, attn_weights = model(X_test)

# Inverse scaling to get real prices
p7_prices = scaler.inverse_transform(p7[:, 0].reshape(-1, 1))
actual_prices = scaler.inverse_transform(y7_test[:, 0].reshape(-1, 1))

# Directional Accuracy (Did we guess the trend?)
pred_dir = np.diff(p7_prices, axis=0) > 0
actual_dir = np.diff(actual_prices, axis=0) > 0
dir_acc = np.mean(pred_dir == actual_dir)

# Realistic Profit (Subtracting Costs)
gross_returns = (actual_prices[1:] - actual_prices[:-1]) / actual_prices[:-1]
net_returns = gross_returns - (TRANSACTION_COST + SLIPPAGE)

print(f"Evaluation Results for 2nd Presentation:")
print(f"7-Day Directional Accuracy: {dir_acc * 100:.2f}%")
print(f"Simulated Net Profit (Adjusted for Slippage): {net_returns.mean()*100:.4f}% per trade")

# Extract attention from a specific prediction
sample_idx = -1 # Latest data point
sample_attn = torch.mean(attn_weights[sample_idx], dim=1).detach().numpy()

plt.figure(figsize=(15, 2))
sns.heatmap(sample_attn.reshape(1, -1), cmap='magma', cbar=True)
plt.title("Explainability Map: Transformer Attention Weights for 30-Day Forecast")
plt.xlabel("Days in the Past (0-60)")
plt.show()

"""# Task
Implement ARIMA and SARIMA models, calculate MAPE and RMSE for all models (Prophet, Hybrid Deep Learning, ARIMA, SARIMA), visualize model performance and accuracy, and compare trends learned by Prophet and the Deep Learning model. Finally, provide a summary of the implementation, metrics, and trend comparison, along with insights from the evaluation.

## Implement ARIMA Model

### Subtask:
Train and evaluate an ARIMA model on the stock data. This will involve selecting appropriate ARIMA parameters (p, d, q) and fitting the model to the training data. Then, generate predictions for the test set.

**Reasoning**:
The subtask requires implementing an ARIMA model. I will import the necessary class, define the model parameters, instantiate and fit the model on the training data, and then generate predictions for the test set as instructed.
"""

from statsmodels.tsa.arima.model import ARIMA

# Determine ARIMA order (p, d, q)
# As per instruction, d=1 for first-order differencing.
# For p and q, we'll start with a common autoregressive order.
order = (5, 1, 0) # Example: AR(5) model with 1st order differencing

print(f"Training ARIMA model with order {order}...")

# Instantiate and fit the ARIMA model
arima_model = ARIMA(train_data['Close'], order=order)
arima_fit = arima_model.fit()

# Generate predictions for the test set
arima_predictions = arima_fit.forecast(steps=len(test_data))

print("ARIMA model trained and predictions generated.")

"""**Reasoning**:
The previous code generated warnings about the date index lacking frequency information. To ensure proper handling by `statsmodels.tsa.arima.model.ARIMA` and avoid future errors, I will explicitly set the frequency of the `train_data` index to daily before fitting the model. This will allow the `ARIMA` model to correctly use the date index for forecasting.


"""

from statsmodels.tsa.arima.model import ARIMA

# Determine ARIMA order (p, d, q)
# As per instruction, d=1 for first-order differencing.
# For p and q, we'll start with a common autoregressive order.
order = (5, 1, 0) # Example: AR(5) model with 1st order differencing

print(f"Training ARIMA model with order {order}...")

# Ensure the training data has a frequency for the ARIMA model to use the index correctly
# Stock data is usually daily, so we can set the frequency to 'D' (daily)
# Use .asfreq('D') to explicitly set the frequency and reindex if necessary
# Fill any potential NaNs created by asfreq if there are gaps (though unlikely with yfinance)
train_data_freq = train_data['Close'].asfreq('D')

# Instantiate and fit the ARIMA model
arima_model = ARIMA(train_data_freq, order=order)
arima_fit = arima_model.fit()

# Generate predictions for the test set
# To get predictions for the actual dates in test_data, we need to specify start and end dates
start_index = len(train_data_freq)
end_index = len(train_data_freq) + len(test_data) - 1

arima_predictions = arima_fit.predict(start=start_index, end=end_index)

# Align predictions with test_data index for easier comparison later
arima_predictions.index = test_data.index

print("ARIMA model trained and predictions generated.")

"""## Implement SARIMA Model

### Subtask:
Train and evaluate a Seasonal ARIMA (SARIMA) model, considering the seasonality observed in the stock data. This will involve selecting SARIMA parameters (p, d, q)(P, D, Q, S) and fitting the model to the training data, followed by predictions for the test set.

**Reasoning**:
I need to import the `SARIMAX` class, define the `order` and `seasonal_order` parameters, instantiate and fit the SARIMA model to the `train_data_freq`, and then generate predictions for the test set, aligning their index with `test_data.index`.
"""

from statsmodels.tsa.statespace.sarimax import SARIMAX

# Define SARIMA order (p, d, q)(P, D, Q, S)
# d=1 for first-order differencing as before.
# S=7 for weekly seasonality (for daily stock data)
order = (5, 1, 0) # Non-seasonal ARIMA order (p, d, q)
seasonal_order = (1, 1, 0, 7) # Seasonal ARIMA order (P, D, Q, S)

print(f"Training SARIMA model with order {order} and seasonal order {seasonal_order}...")

# Instantiate and fit the SARIMA model
sarima_model = SARIMAX(train_data_freq, order=order, seasonal_order=seasonal_order, enforce_stationarity=False, enforce_invertibility=False)
sarima_fit = sarima_model.fit(disp=False)

# Generate predictions for the test set
# Ensure the start and end indices are correct for the test period
start_index = len(train_data_freq)
end_index = len(train_data_freq) + len(test_data) - 1

sarima_predictions = sarima_fit.predict(start=start_index, end=end_index)

# Align predictions with test_data index for easier comparison later
sarima_predictions.index = test_data.index

print("SARIMA model trained and predictions generated.")

"""**Reasoning**:
Now that SARIMA predictions are generated, I need to calculate the Mean Absolute Percentage Error (MAPE) and Root Mean Squared Error (RMSE) for all models to evaluate their performance. I will start with Prophet.


"""

from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error

# Prepare Prophet predictions for evaluation
# Align Prophet forecast with test_data index
prophet_forecast_test = forecast[forecast['ds'].isin(test_data.index)][['ds', 'yhat']]
prophet_forecast_test = prophet_forecast_test.set_index('ds')
prophet_forecast_test.index.name = 'Date'

# Ensure the data is aligned and handle potential missing dates by reindexing
# and filling NaNs if test_data contains dates not in prophet_forecast_test due to holiday/weekend filtering by Prophet.
# For a fair comparison, we'll align based on common dates.
common_dates = test_data.index.intersection(prophet_forecast_test.index)
actual_prophet = test_data.loc[common_dates, 'Close']
predicted_prophet = prophet_forecast_test.loc[common_dates, 'yhat']

# Calculate MAPE for Prophet
mape_prophet = mean_absolute_percentage_error(actual_prophet, predicted_prophet)

# Calculate RMSE for Prophet
rmse_prophet = np.sqrt(mean_squared_error(actual_prophet, predicted_prophet))

print(f"Prophet Model - MAPE: {mape_prophet:.4f}, RMSE: {rmse_prophet:.4f}")

"""**Reasoning**:
Now, I will calculate the MAPE and RMSE for the Hybrid Deep Learning model. I will use the `p7_prices` (7-day predictions) as the model's output and `actual_prices` for the true values from the test set. I'll ensure both arrays are flattened and aligned for proper metric calculation.


"""

import numpy as np

# Prepare Hybrid Deep Learning predictions for evaluation
# p7_prices and actual_prices are already inverse scaled and aligned

# Flatten the arrays to be 1D for metric calculation if they are not already
predicted_hybrid = p7_prices.flatten()
actual_hybrid = actual_prices.flatten()

# Calculate MAPE for Hybrid Deep Learning Model
mape_hybrid = mean_absolute_percentage_error(actual_hybrid, predicted_hybrid)

# Calculate RMSE for Hybrid Deep Learning Model
rmse_hybrid = np.sqrt(mean_squared_error(actual_hybrid, predicted_hybrid))

print(f"Hybrid Deep Learning Model - MAPE: {mape_hybrid:.4f}, RMSE: {rmse_hybrid:.4f}")

"""**Reasoning**:
Next, I will calculate the Mean Absolute Percentage Error (MAPE) and Root Mean Squared Error (RMSE) for the ARIMA model. I will use the `arima_predictions` and the `test_data['Close']` for evaluation, ensuring they are aligned by index.


"""

import numpy as np

# Prepare ARIMA predictions for evaluation
# arima_predictions are already aligned with test_data.index
actual_arima = test_data['Close']
predicted_arima = arima_predictions

# Calculate MAPE for ARIMA Model
mape_arima = mean_absolute_percentage_error(actual_arima, predicted_arima)

# Calculate RMSE for ARIMA Model
rmse_arima = np.sqrt(mean_squared_error(actual_arima, predicted_arima))

print(f"ARIMA Model - MAPE: {mape_arima:.4f}, RMSE: {rmse_arima:.4f}")

"""**Reasoning**:
Now, I will calculate the Mean Absolute Percentage Error (MAPE) and Root Mean Squared Error (RMSE) for the SARIMA model, similar to the previous models. I will use the `sarima_predictions` and the `test_data['Close']` for evaluation, ensuring they are aligned by index.


"""

import numpy as np

# Prepare SARIMA predictions for evaluation
# sarima_predictions are already aligned with test_data.index
actual_sarima = test_data['Close']
predicted_sarima = sarima_predictions

# Calculate MAPE for SARIMA Model
mape_sarima = mean_absolute_percentage_error(actual_sarima, predicted_sarima)

# Calculate RMSE for SARIMA Model
rmse_sarima = np.sqrt(mean_squared_error(actual_sarima, predicted_sarima))

print(f"SARIMA Model - MAPE: {mape_sarima:.4f}, RMSE: {rmse_sarima:.4f}")

"""**Reasoning**:
Now that I have calculated the evaluation metrics for all models, the next step is to visualize their performance. I will start by plotting the actual stock prices against the Prophet model's predictions to visually assess its accuracy and trend capturing ability.


"""

plt.figure(figsize=(16, 8))
plt.plot(train_data.index, train_data['Close'], label='Training Data')
plt.plot(test_data.index, test_data['Close'], label='Actual Prices', color='blue')
plt.plot(predicted_prophet.index, predicted_prophet, label='Prophet Forecast', color='green', linestyle='--')

plt.title('Prophet Model Forecast vs Actual Prices')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.grid(True)
plt.show()

print("Plotting Prophet model's forecast against actual prices.")

"""**Reasoning**:
Now, I will visualize the performance of the Hybrid Deep Learning model by plotting its predictions against the actual stock prices from the test set. This will allow for a visual assessment of its accuracy.


"""

plt.figure(figsize=(16, 8))
plt.plot(train_data.index, train_data['Close'], label='Training Data')
plt.plot(test_data.index, test_data['Close'], label='Actual Prices', color='blue')

# For Hybrid Deep Learning, predicted_hybrid is a flattened numpy array
# We need to create a pandas Series with the correct index for plotting
predicted_hybrid_series = pd.Series(predicted_hybrid, index=test_data.index[:len(predicted_hybrid)])
plt.plot(predicted_hybrid_series.index, predicted_hybrid_series, label='Hybrid DL Forecast', color='red', linestyle='--')

plt.title('Hybrid Deep Learning Model Forecast vs Actual Prices')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.grid(True)
plt.show()

print("Plotting Hybrid Deep Learning model's forecast against actual prices.")

"""**Reasoning**:
Now, I will visualize the performance of the ARIMA model by plotting its predictions against the actual stock prices from the test set. This will allow for a visual assessment of its accuracy.


"""

plt.figure(figsize=(16, 8))
plt.plot(train_data.index, train_data['Close'], label='Training Data')
plt.plot(test_data.index, test_data['Close'], label='Actual Prices', color='blue')
plt.plot(predicted_arima.index, predicted_arima, label='ARIMA Forecast', color='purple', linestyle='--')

plt.title('ARIMA Model Forecast vs Actual Prices')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.grid(True)
plt.show()

print("Plotting ARIMA model's forecast against actual prices.")

"""**Reasoning**:
Now, I will visualize the performance of the SARIMA model by plotting its predictions against the actual stock prices from the test set. This will allow for a visual assessment of its accuracy.


"""

plt.figure(figsize=(16, 8))
plt.plot(train_data.index, train_data['Close'], label='Training Data')
plt.plot(test_data.index, test_data['Close'], label='Actual Prices', color='blue')
plt.plot(predicted_sarima.index, predicted_sarima, label='SARIMA Forecast', color='orange', linestyle='--')

plt.title('SARIMA Model Forecast vs Actual Prices')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.grid(True)
plt.show()

print("Plotting SARIMA model's forecast against actual prices.")

"""**Reasoning**:
Now that individual plots for each model's predictions have been generated, I will create a single plot to visualize the performance of all four models (Prophet, Hybrid Deep Learning, ARIMA, and SARIMA) against the actual prices in the test set. This will allow for a direct visual comparison of their accuracy and trend-following capabilities.


"""

plt.figure(figsize=(18, 10))
plt.plot(train_data.index, train_data['Close'], label='Training Data', color='gray', alpha=0.7)
plt.plot(test_data.index, test_data['Close'], label='Actual Prices (Test Set)', color='blue', linewidth=2)
plt.plot(predicted_prophet.index, predicted_prophet, label='Prophet Forecast', color='green', linestyle='--')

# Ensure predicted_hybrid_series covers the same period as test_data for accurate plotting
# (Already created in a previous step, so just plot it)
plt.plot(predicted_hybrid_series.index, predicted_hybrid_series, label='Hybrid DL Forecast', color='red', linestyle='-.')

plt.plot(predicted_arima.index, predicted_arima, label='ARIMA Forecast', color='purple', linestyle=':')
plt.plot(predicted_sarima.index, predicted_sarima, label='SARIMA Forecast', color='orange', linestyle='--')

plt.title('All Models Forecast vs Actual Prices', fontsize=18)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Stock Price', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True)
plt.tight_layout()
plt.show()

print("Plotting all models' forecasts against actual prices for comparison.")

"""## Visualize Model Performance Comparison

### Subtask:
Visualize the calculated MAPE and RMSE for each model using bar charts to clearly compare their accuracy.

**Reasoning**:
I will create data structures to hold the calculated MAPE and RMSE values for each model, then visualize them using bar charts to compare their performance as per the subtask instructions.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Create a dictionary to store MAPE values
mape_data = {
    'Model': ['Prophet', 'Hybrid DL', 'ARIMA', 'SARIMA'],
    'MAPE': [mape_prophet, mape_hybrid, mape_arima, mape_sarima]
}

# 2. Create another dictionary to store RMSE values
rmse_data = {
    'Model': ['Prophet', 'Hybrid DL', 'ARIMA', 'SARIMA'],
    'RMSE': [rmse_prophet, rmse_hybrid, rmse_arima, rmse_sarima]
}

# Convert to DataFrame for easier plotting
mape_df = pd.DataFrame(mape_data)
rmse_df = pd.DataFrame(rmse_data)

# 3. Generate two bar charts side-by-side
plt.figure(figsize=(18, 7))

plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.barplot(x='Model', y='MAPE', data=mape_df, palette='viridis')
plt.title('Model Comparison - Mean Absolute Percentage Error (MAPE)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('MAPE', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.barplot(x='Model', y='RMSE', data=rmse_df, palette='magma')
plt.title('Model Comparison - Root Mean Squared Error (RMSE)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('RMSE', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

print("Generated bar charts comparing MAPE and RMSE for all models.")

"""**Reasoning**:
The previous code generated a `FutureWarning` from seaborn regarding the `palette` argument without `hue`. To fix this, I will explicitly set `hue='Model'` and `legend=False` in the `sns.barplot` calls as suggested by the warning.


"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Create a dictionary to store MAPE values
mape_data = {
    'Model': ['Prophet', 'Hybrid DL', 'ARIMA', 'SARIMA'],
    'MAPE': [mape_prophet, mape_hybrid, mape_arima, mape_sarima]
}

# 2. Create another dictionary to store RMSE values
rmse_data = {
    'Model': ['Prophet', 'Hybrid DL', 'ARIMA', 'SARIMA'],
    'RMSE': [rmse_prophet, rmse_hybrid, rmse_arima, rmse_sarima]
}

# Convert to DataFrame for easier plotting
mape_df = pd.DataFrame(mape_data);
rmse_df = pd.DataFrame(rmse_data)

# 3. Generate two bar charts side-by-side
plt.figure(figsize=(18, 7))

plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.barplot(x='Model', y='MAPE', data=mape_df, palette='viridis', hue='Model', legend=False)
plt.title('Model Comparison - Mean Absolute Percentage Error (MAPE)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('MAPE', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.barplot(x='Model', y='RMSE', data=rmse_df, palette='magma', hue='Model', legend=False)
plt.title('Model Comparison - Root Mean Squared Error (RMSE)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('RMSE', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

print("Generated bar charts comparing MAPE and RMSE for all models.")

"""## Compare Trends Learned by Prophet vs. Deep Learning Model

### Subtask:
Extract the trend component from the Prophet model's forecast and infer the trend from the Deep Learning model. Create a visualization comparing these trends over a common period to highlight similarities or differences in their long-term predictions or underlying trend assumptions.

**Reasoning**:
I need to extract the trend component from the Prophet model's forecast, infer a smoothed trend from the Hybrid Deep Learning model's predictions, and then visualize both alongside the actual test data to compare their learned trends. I will start by extracting the Prophet trend and calculating the rolling mean for the Hybrid DL trend.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Extract Prophet's trend component for the test period
prophet_trend = forecast[forecast['ds'].isin(test_data.index)][['ds', 'trend']]
prophet_trend = prophet_trend.set_index('ds')
prophet_trend.index.name = 'Date'

# Ensure prophet_trend is aligned with test_data index for plotting
common_dates_prophet_trend = test_data.index.intersection(prophet_trend.index)
prophet_trend_aligned = prophet_trend.loc[common_dates_prophet_trend, 'trend']

# 2. Infer trend from Hybrid Deep Learning model (using a rolling mean)
# The 'predicted_hybrid_series' already has the correct index and data
rolling_window = 30 # Example: 30-day rolling mean for smoothing
hybrid_dl_trend = predicted_hybrid_series.rolling(window=rolling_window, center=True).mean()

# 3. Create a single plot comparing these trends
plt.figure(figsize=(16, 8))
plt.plot(test_data.index, test_data['Close'], label='Actual Prices (Test Set)', color='blue', linewidth=2)
plt.plot(prophet_trend_aligned.index, prophet_trend_aligned, label='Prophet Trend', color='green', linestyle='--')
plt.plot(hybrid_dl_trend.index, hybrid_dl_trend, label='Hybrid DL Trend (30-Day Rolling Mean)', color='red', linestyle='-.')

# 4. Add title, labels, and legend
plt.title('Comparison of Learned Trends: Prophet vs. Hybrid DL', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Stock Price', fontsize=12)
plt.legend(fontsize=10)
plt.grid(True)
plt.tight_layout()
plt.show()

print("Visualization comparing Prophet and Hybrid DL trends generated.")